### ISSUE TITLE
V 1.3.1 on PyPi?

### ISSUE THREAD

**Issue by zbeekman** [UMIACS/umobj#1]
I can't seem to find 1.3.1 on PyPi. I was going to update the UMIACS homebrew tap, but need to know the URL and SHA256 hash of the PyPi hosted tarball.

**Comment by liammonahan** [comment]
Hi Izaak,

Sorry.  It's up there now.

https://pypi.python.org/pypi/umobj/1.3.1

Thanks,
Liam

**Comment by zbeekman** [comment]
thanks!
