### ISSUE TITLE
Unexpected Behaviors of The Commands

### ISSUE THREAD

**Issue by Sanghyun-Hong** [UMIACS/umobj#3]
I have an issue with the 'rmobj' command, which shows unexpected behaviors ...
`rmobj -r <mybucket>:<myfolder>/abc`

The command above removes all the subdirectories that start with **abc** (e.g., **abc**, **abcde**, **abcxx**, and so on) under the _myfolder_ directory.

I think it should remove only the directories under '**abc**', not the others...

**Comment by liammonahan** [comment]
Hi,

A fix for this was merged on our gitlab project recently.[0]  It will be released soon.  I will let you know when that happens!  Thank you for reporting this!

~Liam

[0]- https://gitlab.umiacs.umd.edu/staff/umobj/issues/48

**Comment by liammonahan** [comment]
Hi,

This has been released as umobj-1.6.0.  All UMIACS hosts should be updating now to the latest version.  If you're using this on a personal machine you can also run `pip install --upgrade umobj` to get the latest version.  Thanks again.

Liam

-- https://github.com/UMIACS/umobj/releases/tag/1.6.0
